### ISSUE TITLE
Exception on SubscribeAsync()

### ISSUE THREAD

**Issue by danielhw2** [ridicoulous/Bitmex.NET#46]
When I call SubscribeAsync() it returns a exception...

The Code:
```
var Req = new BitmexSubscribeRequest();
Req.AddSubscription(Bitmex.Net.Client.Objects.Socket.BitmexSubscribtions.Announcements); 
Req.AddSubscription(Bitmex.Net.Client.Objects.Socket.BitmexSubscribtions.PublicNotifications); 
Req.AddSubscription(Bitmex.Net.Client.Objects.Socket.BitmexSubscribtions.Connected);
Req.AddSubscription(Bitmex.Net.Client.Objects.Socket.BitmexSubscribtions.Order); 
Req.AddSubscription(Bitmex.Net.Client.Objects.Socket.BitmexSubscribtions.Margin);
Req.AddSubscription(Bitmex.Net.Client.Objects.Socket.BitmexSubscribtions.Wallet); 
Req.AddSubscription(Bitmex.Net.Client.Objects.Socket.BitmexSubscribtions.Position); 
Req.AddSubscription(Bitmex.Net.Client.Objects.Socket.BitmexSubscribtions.Transact); 
var Resposta = ClienteSocket.SubscribeAsync(Req, CancellationToken.None).Result;
```

The error message:
```
System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred. (Object reference not set to an instance of an object.)
  Source=System.Private.CoreLib
  StackTrace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
...
 This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
NullReferenceException: Object reference not set to an instance of an object.
```

Using the latest versions:
Bitmex.Net.Client 3.0.0
CryptoExchange.Net 6.1.4

**Comment by alokym86** [comment]
Unfortunately, I cannot reproduce your exception.

**Comment by danielhw2** [comment]
Thank you... After your message I investigated further and I found an error in my code... Thanks!!!
